[tool.black]
line-length = 79

[tool.isort]
multi_line_output = 3
include_trailing_comma = true

[tool.mypy]
strict = true
disallow_untyped_decorators = false
python_version = "3.9"

[tool.pylint.master]
jobs = 0

[tool.pylint.message_control]
disable = [
    "import-error",  # for pre-commit, which cannot install external modules
    "no-member",  # leave type checking to mypy
    "signature-differs",  # leave type checking to mypy
    "duplicate-code",
    "too-few-public-methods",
    "too-many-instance-attributes",
]
